export default {
  "PAIRING_NUMBER": "447777331420",
  "MONGODB_URI": "",
  "AUTO_VIEW_STATUS": true,
  "AUTO_RECORDING": false,
  "AUTO_TYPING": false,
  "AUTO_VOICE": false,
  "AUTO_STICKER": true,
  "ALWAYS_ONLINE": false,
  "PREFIX": ".",
  "IMAGE_PATH": "./media/",
  "BOT_NAME": "WhatsApp Bot",
  "OWNER_NAME": "SOG-X",
  "OWNER_NUMBER": "",
  "BOT_FOOTER": "Powered by WhatsApp Bot",
  "AUTO_REJECT_CALLS": false,
  "SEND_REJECT_MESSAGE": true,
  "REJECT_CALL_MESSAGE": "Sorry, I don't accept calls",
  "AUTO_READ_MESSAGES": false,
  "AUTO_REACT_MESSAGES": true,
  "BLOCK_91_NUMBERS": false,
  "ANTI_LINK": false,
  "ANTI_BOT": true,
  "DP_CHANGE_REPORT": true,
  "AUTO_SPAM_BLOCK": true
};